# Promise 链

新手常犯的一个经典错误：从技术上讲，我们也可以将多个 .then 添加到一个 promise 上。但这并不是 promise 链（chaining）。

## 更复杂的示例：fetch

# 使用 promise 进行错误处理

.catch 不必是立即的。它可能在一个或多个 .then 之后出现。

## 隐式 try…catch

## 再次抛出（Rethrowing）

## 未处理的 rejection

JavaScript 引擎会跟踪此类 rejection，在这种情况下会生成一个全局的 error。如果你运行上面这个代码，你可以在控制台（console）中看到。

在浏览器中，我们可以使用 unhandledrejection 事件来捕获这类 error

# Promise API

 Promise类中，有6种静态方法。

 ## Promise.all

 ```js
 let promise = Promise.all([...promise...]);
 ```

 ## Promise.allSettled

 Poly

 ```js
if (!Promise.allSettled) {
  const rejectHandler = reason => ({ status: 'rejectd', reason});
  const resolveHandler = value => ({ status: 'fulfilled', value});

  Promise.allSettled = function (promise) {
    const convertedPromises = promise.map(p => Promise.resolve(p).then(resolveHandler, rejectHandler));
    return Promise.all(convertedPromises);
  };
}
 ```

 ## Promise.race

 与 Promise.all 类似，但只等待第一个 settled 的 promise 并获取其结果（或 error）。

 ## Promise.any

 与 Promise.race 类似，区别在于 Promise.any 只等待第一个 fulfilled 的 promise，并将这个 fulfilled 的 promise 返回。

```js
let promise = Promise.any(iterable);
```

## Promise.resolve/reject

在现代的代码中，很少需要使用 Promise.resolve 和 Promise.reject 方法，因为 async/await 语法（我们会在 稍后 讲到）使它们变得有些过时了。

### Promise.resolve

Promise.resolve(value) 用结果 value 创建一个 resolved 的 promise。

`let promise = new Promise(resolve => resolve(value));`

## Promise.reject

Promise.reject(error) 用 error 创建一个 rejected 的 promise。

`let promise = new Promise((resolve, reject) => reject(error));`

实际上，这个方法几乎从未被使用过。